# -*- coding: utf-8 -*-
"""ProyectoFinal_Redes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gZVEwK5D2MVwVUr1Brwl4xK00wLiol88

# Instalación de dependencias
"""

import wfdb
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns
from scipy import signal
import pywt
from collections import Counter
from datetime import datetime
import warnings
from pathlib import Path
from imblearn.over_sampling import SMOTE
warnings.filterwarnings('ignore')

# Importación de smote
try:
    from imblearn.over_sampling import SMOTE
    SMOTE_AVAILABLE = True
except ImportError:
    print("SMOTE no disponible.")
    SMOTE_AVAILABLE = False

"""# Extracción y visualización de datos

"""

# Variables globales para CSV
CSV_FILE = "ecg_live_capture_20260706_181344.csv"
USE_CSV = Path(CSV_FILE).exists()

def cargar_csv_ecg(filepath):
    """Carga ECG desde un archivo CSV local"""
    try:
        df = pd.read_csv(filepath)
        
        # Estructura de clase simple para compatibilidad
        class RecordCSV:
            def __init__(self, data):
                self.p_signal = data['ecg_filtrado'].values.reshape(-1, 1)
                self.fs = 360.23  # Frecuencia de muestreo del CSV
                self.n_sig = 1
                self.sig_name = ['ECG']
        
        class AnnotationCSV:
            def __init__(self):
                self.sample = np.array([])
                self.symbol = np.array([])
        
        record = RecordCSV(df)
        annotation = AnnotationCSV()
        return record, annotation
    except Exception as e:
        print(f"Error cargando CSV {filepath}: {e}")
        return None, None

def cargar_registro_ecg(numero_registro):
    """Carga un registro ECG de la base MIT-BIH"""
    try:
        record = wfdb.rdrecord(str(numero_registro), pn_dir='mitdb')
        annotation = wfdb.rdann(str(numero_registro), 'atr', pn_dir='mitdb')
        return record, annotation
    except Exception as e:
        print(f"Error cargando registro {numero_registro}: {e}")
        return None, None

# Cargar registro de ejemplo
print("ANÁLISIS DE ECG - BASE DE DATOS MIT-BIH")

if USE_CSV:
    print(f"\n[CSV] Usando CSV local: {CSV_FILE}")
    record, annotation = cargar_csv_ecg(CSV_FILE)
else:
    record, annotation = cargar_registro_ecg(105)

if record is not None:
    print(f"\n INFORMACIÓN DEL REGISTRO")
    print(f"Número de señales: {record.n_sig}")
    print(f"Frecuencia de muestreo: {record.fs} Hz")
    print(f"Duración: {len(record.p_signal) / record.fs:.2f} segundos")
    print(f"Nombres de señales: {record.sig_name}")
    if len(annotation.symbol) > 0:
        print(f"Anotaciones disponibles: {set(annotation.symbol)}")

        # Contar tipos de latidos
        contador_latidos = Counter(annotation.symbol)
        print("\n Distribución de tipos de latidos:")
        for tipo, cantidad in contador_latidos.most_common():
            print(f"  {tipo}: {cantidad} ({cantidad/len(annotation.symbol)*100:.1f}%)")
    else:
        print("\n (Sin anotaciones disponibles - Análisis explorador)")

    # Visualización mejorada
    plt.figure(figsize=(16, 10))

    # Señal ECG completa
    plt.subplot(3, 1, 1)
    tiempo = np.arange(len(record.p_signal)) / record.fs
    plt.plot(tiempo, record.p_signal[:, 0], linewidth=0.5)
    plt.title('Señal ECG Completa', fontsize=14, fontweight='bold')
    plt.xlabel('Tiempo (s)')
    plt.ylabel('Amplitud (mV)')
    plt.grid(True, alpha=0.3)

    # Zoom en primeros 10 segundos con anotaciones
    plt.subplot(3, 1, 2)
    tiempo_max = 40  # 10 segundos
    samples_max = int(tiempo_max * record.fs)
    plt.plot(tiempo[:samples_max], record.p_signal[:samples_max, 0])
    plt.title(f'Detalle - Primeros {tiempo_max} segundos',
              fontsize=12, fontweight='bold')
    plt.xlabel('Tiempo (s)')
    plt.ylabel('Amplitud (mV)')
    plt.grid(True, alpha=0.3)

    # Marcar latidos anotados en la ventana de tiempo (si hay anotaciones)
    if len(annotation.symbol) > 0:
        latidos_tiempo = annotation.sample / record.fs
        latidos_simbolo = np.array(annotation.symbol)  # Convertir a array NumPy

        mask = latidos_tiempo < tiempo_max
        colores = {'N': 'green', 'V': 'red', 'A': 'blue', 'L': 'orange', 'R': 'purple'}

        for t, sym in zip(latidos_tiempo[mask], latidos_simbolo[mask]):
            color = colores.get(sym, 'gray')
            plt.axvline(x=t, color=color, alpha=0.5, linestyle='--', linewidth=1)
            plt.text(t, plt.ylim()[1]*0.9, sym, fontsize=9, color=color,
                    ha='center', fontweight='bold')

        # Distribución de tipos de latidos
        plt.subplot(3, 1, 3)
        contador_latidos = Counter(annotation.symbol)
        tipos = list(contador_latidos.keys())
        cantidades = list(contador_latidos.values())
        colores_barras = [colores.get(t, 'gray') for t in tipos]

        plt.bar(tipos, cantidades, color=colores_barras, alpha=0.7, edgecolor='black')
        plt.title('Distribución de Tipos de Latidos', fontsize=12, fontweight='bold')
        plt.xlabel('Tipo de Latido')
        plt.ylabel('Cantidad')
        plt.grid(True, alpha=0.3, axis='y')

        for i, (tipo, cant) in enumerate(zip(tipos, cantidades)):
            plt.text(i, cant, str(cant), ha='center', va='bottom', fontweight='bold')
    else:
        # Para CSV sin anotaciones: mostrar espectro de potencia
        plt.subplot(3, 1, 3)
        senal_filt = record.p_signal[:, 0] - np.mean(record.p_signal[:, 0])
        f, Pxx = signal.welch(senal_filt, record.fs, nperseg=1024)
        plt.semilogy(f, Pxx)
        plt.title('Espectro de Potencia', fontsize=12, fontweight='bold')
        plt.xlabel('Frecuencia (Hz)')
        plt.ylabel('Potencia (V²/Hz)')
        plt.xlim(0, 50)
        plt.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('visualizacion_ecg.png', dpi=150, bbox_inches='tight')
    print("[OK] Grafico guardado: visualizacion_ecg.png")

"""# Preprocesamiento de señales"""

def preprocesar_ecg(senal, fs=360):
    """Aplica preprocesamiento a la señal ECG"""
    # Remover componente DC
    senal = senal - np.mean(senal)

    # Filtro pasa banda (0.5 - 40 Hz) para eliminar ruido
    nyquist = fs / 2
    low = 0.5 / nyquist
    high = 40.0 / nyquist
    b, a = signal.butter(3, [low, high], btype='band')
    senal_filtrada = signal.filtfilt(b, a, senal)

    return senal_filtrada

def extraer_caracteristicas_avanzadas(senal, fs=360):
    """Extrae características avanzadas de la señal ECG"""
    caracteristicas = {}

    #  Características estadísticas básicas
    caracteristicas['media'] = np.mean(senal)
    caracteristicas['std'] = np.std(senal)
    caracteristicas['rms'] = np.sqrt(np.mean(senal**2))
    caracteristicas['max'] = np.max(senal)
    caracteristicas['min'] = np.min(senal)
    caracteristicas['rango'] = np.max(senal) - np.min(senal)
    caracteristicas['skewness'] = pd.Series(senal).skew()
    caracteristicas['kurtosis'] = pd.Series(senal).kurtosis()

    #  Características espectrales
    try:
        f, Pxx = signal.welch(senal, fs, nperseg=min(256, len(senal)))
        caracteristicas['frecuencia_dominante'] = f[np.argmax(Pxx)]
        caracteristicas['potencia_espectral'] = np.sum(Pxx)
        caracteristicas['entropia_espectral'] = -np.sum(Pxx * np.log2(Pxx + 1e-10))
    except Exception as e:
        caracteristicas['frecuencia_dominante'] = 0
        caracteristicas['potencia_espectral'] = 0
        caracteristicas['entropia_espectral'] = 0

    # Características de wavelet
    try:
        coeffs = pywt.wavedec(senal, 'db4', level=4)
        for i, coeff in enumerate(coeffs):
            caracteristicas[f'energia_wavelet_nivel_{i}'] = np.sum(np.square(coeff))
    except Exception as e:
        for i in range(5):
            caracteristicas[f'energia_wavelet_nivel_{i}'] = 0

    # Características de dominio del tiempo (HRV)
    try:
        # Detectar picos R
        peaks, _ = signal.find_peaks(senal, distance=int(fs*0.6), height=np.max(senal)*0.3)

        if len(peaks) > 1:
            rr_intervals = np.diff(peaks) / fs * 1000  # Convertir a ms

            caracteristicas['rr_mean'] = np.mean(rr_intervals)
            caracteristicas['rr_std'] = np.std(rr_intervals)
            caracteristicas['rr_min'] = np.min(rr_intervals)
            caracteristicas['rr_max'] = np.max(rr_intervals)

            # RMSSD - Raíz cuadrada de la media de diferencias al cuadrado
            if len(rr_intervals) > 1:
                caracteristicas['hrv_rmssd'] = np.sqrt(np.mean(np.diff(rr_intervals)**2))
            else:
                caracteristicas['hrv_rmssd'] = 0

            # pNN50 - Porcentaje de intervalos RR que difieren más de 50ms
            diff_rr = np.abs(np.diff(rr_intervals))
            caracteristicas['pnn50'] = np.sum(diff_rr > 50) / len(diff_rr) * 100
        else:
            # Si no se detectan picos suficientes
            for key in ['rr_mean', 'rr_std', 'rr_min', 'rr_max', 'hrv_rmssd', 'pnn50']:
                caracteristicas[key] = 0
    except Exception as e:
        for key in ['rr_mean', 'rr_std', 'rr_min', 'rr_max', 'hrv_rmssd', 'pnn50']:
            caracteristicas[key] = 0

    return caracteristicas

"""# Extracción de latidos"""

def extraer_latidos(senal, anotaciones, fs=360, ventana=180):
    # Extracción de ventanas de latidos individuales
    latidos = []
    etiquetas = []

    # Si hay anotaciones (base MIT-BIH)
    if len(anotaciones.symbol) > 0:
        for i, muestra in enumerate(anotaciones.sample):
            inicio = muestra - ventana
            fin = muestra + ventana

            # Validación de índices
            if inicio >= 0 and fin < len(senal):
                latido = senal[inicio:fin]
                if len(latido) == ventana * 2:  # Solo latidos completos
                    latidos.append(latido)
                    etiquetas.append(anotaciones.symbol[i])
    else:
        # Sin anotaciones: detectar picos automáticamente (para CSV)
        senal_norm = (senal - np.mean(senal)) / np.std(senal)
        threshold = np.mean(senal_norm) + 1.5 * np.std(senal_norm)
        peaks, _ = signal.find_peaks(senal_norm, height=threshold, distance=int(fs * 0.3))
        
        for peak in peaks:
            inicio = peak - ventana
            fin = peak + ventana
            
            if inicio >= 0 and fin < len(senal):
                latido = senal[inicio:fin]
                if len(latido) == ventana * 2:
                    latidos.append(latido)
                    etiquetas.append('N')  # Etiquetar como normal por defecto

    return np.array(latidos), etiquetas

"""# Procesamiento de multiples registros"""

def cargar_multiples_registros(lista_registros=None):
    todos_latidos = []
    todas_etiquetas = []

    print("CARGANDO REGISTROS")

    if USE_CSV:
        # Cargar solo el CSV
        record, annotation = cargar_csv_ecg(CSV_FILE)
        if record is not None:
            senal_filtrada = preprocesar_ecg(record.p_signal[:, 0], fs=record.fs)
            latidos, etiquetas = extraer_latidos(senal_filtrada, annotation, fs=record.fs)
            
            todos_latidos.extend(latidos)
            todas_etiquetas.extend(etiquetas)
            
            print(f"CSV {CSV_FILE}: {len(latidos)} latidos extraídos")
    else:
        # Cargar múltiples registros de MIT-BIH
        if lista_registros is None:
            lista_registros = [100, 101, 103, 105, 106, 108, 109,
                             111, 112, 113, 114, 115, 116, 117, 118, 119]
        
        for registro in lista_registros:
            record, annotation = cargar_registro_ecg(registro)
            if record is not None:
                senal_filtrada = preprocesar_ecg(record.p_signal[:, 0])
                latidos, etiquetas = extraer_latidos(senal_filtrada, annotation)

                todos_latidos.extend(latidos)
                todas_etiquetas.extend(etiquetas)

                print(f"Registro {registro}: {len(latidos)} latidos extraídos")
            else:
                print(f"  Registro {registro}: No se pudo cargar")

    return np.array(todos_latidos), todas_etiquetas

"""# Entrenamiento del modelo"""

def entrenar_modelo_clasificacion(latidos, etiquetas):

    print("ENTRENAMIENTO DEL MODELO")

    # Extraer características de todos los latidos
    print("\n Extrayendo características avanzadas...")
    caracteristicas_lista = []
    etiquetas_filtradas = []

    for i, latido in enumerate(latidos):
        try:
            carac = extraer_caracteristicas_avanzadas(latido)
            caracteristicas_lista.append(list(carac.values()))
            etiquetas_filtradas.append(etiquetas[i])
        except Exception as e:
            continue

        if (i + 1) % 500 == 0:
            print(f"   Procesados: {i+1}/{len(latidos)} latidos...")

    X = np.array(caracteristicas_lista)
    y = np.array(etiquetas_filtradas)

    print(f"\n Características extraídas: {X.shape[1]} features por latido")

    # Filtrar clases con pocas muestras y mapear clases
    contador = Counter(y)
    print(f"\n Distribución original de clases:")
    for clase, count in sorted(contador.items(), key=lambda x: x[1], reverse=True):
        print(f" {clase}: {count} muestras ({count/len(y)*100:.1f}%)")

    # Mantener clases con más de 50 muestras para mejor generalización
    clases_validas = [clase for clase, count in contador.items() if count > 50]
    mascara = np.isin(y, clases_validas)
    X = X[mascara]
    y = y[mascara]

    print(f"\n Clases seleccionadas (>50 muestras): {clases_validas}")
    print(f" Total de muestras después de filtrado: {len(X)}")

    # Balanceo de clases con SMOTE (si está disponible)
    if SMOTE_AVAILABLE and len(clases_validas) > 1:
        print("\n  Aplicando SMOTE para balancear clases...")
        try:
            smote = SMOTE(random_state=42, k_neighbors=min(5, min(Counter(y).values())-1))
            X, y = smote.fit_resample(X, y)
            print(f" Dataset balanceado. Nuevas dimensiones: {X.shape}")

            contador_balanceado = Counter(y)
            print(f"\n Distribución después de SMOTE:")
            for clase, count in sorted(contador_balanceado.items()):
                print(f"   {clase}: {count} muestras")
        except Exception as e:
            print(f"  No se pudo aplicar SMOTE: {e}")

    # Dividir datos
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=42, stratify=y
    )

    print(f"\n División de datos:")
    print(f"   Entrenamiento: {len(X_train)} muestras")
    print(f"   Prueba: {len(X_test)} muestras")

    # Estandarizar características
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Entrenar modelo
    print("\n Entrenando Random Forest...")
    modelo = RandomForestClassifier(
        n_estimators=200,  # Más árboles para mejor rendimiento
        max_depth=20,
        min_samples_split=5,
        min_samples_leaf=2,
        random_state=42,
        n_jobs=-1  # Usar todos los cores
    )
    modelo.fit(X_train_scaled, y_train)
    print(" Modelo entrenado exitosamente")

    # Validación cruzada
    print("\n Realizando validación cruzada (5-fold)...")
    cv_scores = cross_val_score(modelo, X_train_scaled, y_train, cv=5, n_jobs=-1)
    print(f"   Precisión CV: {cv_scores.mean():.4f} (+/- {cv_scores.std():.4f})")
    print(f"   Scores individuales: {[f'{s:.4f}' for s in cv_scores]}")

    # Evaluar modelo
    y_pred = modelo.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)

    print("\n" + "="*70)
    print(" RESULTADOS DEL MODELO")
    print("="*70)
    print(f"\n Precisión en Test: {accuracy:.4f}")
    print("\n Reporte de Clasificación:")
    print(classification_report(y_test, y_pred))

    # Matriz de confusión
    plt.figure(figsize=(12, 10))
    cm = confusion_matrix(y_test, y_pred)

    # Normalizar por filas para ver porcentajes
    cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

    # Crear anotaciones que muestren conteo y porcentaje
    annotations = np.empty_like(cm).astype(str)
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            annotations[i, j] = f'{cm[i,j]}\n({cm_norm[i,j]*100:.1f}%)'

    sns.heatmap(cm_norm, annot=annotations, fmt='', cmap='Blues',
                xticklabels=modelo.classes_,
                yticklabels=modelo.classes_,
                cbar_kws={'label': 'Proporción'},
                vmin=0, vmax=1)
    plt.title('Matriz de Confusión - Clasificación de Arritmias',
              fontsize=14, fontweight='bold')
    plt.xlabel('Predicho', fontsize=12)
    plt.ylabel('Real', fontsize=12)
    plt.tight_layout()
    plt.show()

    # Importancia de características
    feature_names = list(extraer_caracteristicas_avanzadas(latidos[0]).keys())
    importances = modelo.feature_importances_
    indices = np.argsort(importances)[::-1][:15]  # Top 15

    plt.figure(figsize=(12, 6))
    plt.title('Top 15 Características Más Importantes', fontsize=14, fontweight='bold')
    plt.bar(range(15), importances[indices], color='steelblue', alpha=0.7)
    plt.xticks(range(15), [feature_names[i] for i in indices], rotation=45, ha='right')
    plt.ylabel('Importancia')
    plt.xlabel('Característica')
    plt.tight_layout()
    plt.show()

    return modelo, scaler, feature_names

"""# Ejecución principal"""

if __name__ == "__main__":
    # Lista ampliada de registros para mejor entrenamiento
    if not USE_CSV:
        registros_entrenamiento = [100, 101, 103, 105, 106, 108, 109,
                                   111, 112, 113, 114, 115, 116, 117, 118, 119]
        latidos, etiquetas = cargar_multiples_registros(registros_entrenamiento)
    else:
        latidos, etiquetas = cargar_multiples_registros()

    if len(latidos) > 100:  # Asegurar suficientes datos
        print(f"\n Total de latidos extraídos: {len(latidos)}")

        # Entrenar modelo
        modelo, scaler, feature_names = entrenar_modelo_clasificacion(latidos, etiquetas)

        # Guardar modelo con metadatos
        import joblib
        import json

        joblib.dump(modelo, 'modelo_arritmias.pkl')
        joblib.dump(scaler, 'scaler_arritmias.pkl')

        metadata = {
            'fecha_entrenamiento': datetime.now().isoformat(),
            'clases': modelo.classes_.tolist(),
            'num_features': len(feature_names),
            'features': feature_names,
            'num_muestras_entrenamiento': len(latidos),
            'fuente_datos': 'CSV LOCAL' if USE_CSV else 'MIT-BIH DATABASE',
            'archivo_csv': CSV_FILE if USE_CSV else None,
            'registros_utilizados': None if USE_CSV else registros_entrenamiento,
            'version': '2.0'
        }

        with open('metadata_modelo.json', 'w', encoding='utf-8') as f:
            json.dump(metadata, f, indent=2, ensure_ascii=False)

        print(" MODELO GUARDADO")
        print(" modelo_arritmias.pkl")
        print(" scaler_arritmias.pkl")
        print(" metadata_modelo.json")

    else:
        print("\n No se pudieron extraer suficientes latidos para entrenamiento")
        print("   Se requieren al menos 100 latidos")

"""# Clasificación de nuevas señales"""

def clasificar_nuevo_latido(senal, modelo, scaler, fs=360):
    """Clasifica un nuevo latido ECG"""
    senal_preprocesada = preprocesar_ecg(senal, fs)
    caracteristicas = extraer_caracteristicas_avanzadas(senal_preprocesada, fs)

    X_nuevo = np.array(list(caracteristicas.values())).reshape(1, -1)
    X_nuevo_esc = scaler.transform(X_nuevo)

    prediccion = modelo.predict(X_nuevo_esc)
    probabilidades = modelo.predict_proba(X_nuevo_esc)

    return prediccion[0], probabilidades[0]

# Ejemplo de clasificación
if 'modelo' in locals() and len(latidos) > 0:

    print(" PRUEBA DE CLASIFICACIÓN")


    # Probar con varios latidos aleatorios
    indices_prueba = np.random.choice(len(latidos), min(5, len(latidos)), replace=False)

    for idx in indices_prueba:
        latido_prueba = latidos[idx]
        etiqueta_real = etiquetas[idx]
        clase_predicha, prob = clasificar_nuevo_latido(latido_prueba, modelo, scaler)

        print(f"\n[LATIDO] Latido #{idx}:")
        print(f"   Real: {etiqueta_real}")
        print(f"   Predicho: {clase_predicha}")
        print(f"   Confianza: {np.max(prob)*100:.2f}%")
        print(f"   Probabilidades: {dict(zip(modelo.classes_, [f'{p:.3f}' for p in prob]))}")

        if clase_predicha == etiqueta_real:
            print(" CORRECTO")
        else:
            print(" INCORRECTO")

print(" ANÁLISIS COMPLETADO")